name: world-generation
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip==25.0.1
  - pytest==8.3.5
  - pytest-cov==6.0.0
  - ruff==0.11.5
  - mypy==1.15.0
  - pyyaml==6.0.2
  - GitPython==3.1.44
  - contourpy==1.3.0
  - cycler==0.12.1
  - fonttools==4.54.1
  - imageio==2.37.0
  - kiwisolver==1.4.7
  - lazy_loader==0.4
  - llvmlite==0.43.0
  - matplotlib==3.9.2
  - networkx==3.4.2
  - noise==1.2.2
  - numba==0.60.0
  - numpy==2.0.2
  - opencv==4.11.0
  - packaging==24.1
  - pillow==11.0.0
  - pyparsing==3.2.0
  - python-dateutil==2.9.0.post0
  - scikit-image==0.25.1
  - scipy==1.14.1
  - shapely==2.0.7
  - six==1.16.0
  - sortedcontainers==2.4.0
  - tifffile==2025.1.10
  - vedo==2025.5.3
  - tqdm==4.67.1
  - tbb==2022.1.0