# This is a basic workflow to help you get started with Actions

name: Temporary_CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "prism", "theory", "world-generation", "infra"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Add conda to system path
      id: conda_setup
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: LS
      run: ls -l .
    - name: PWD
      run: pwd 
    - name: Install dependencies
      run: |
        conda env update --file environment/environment.yaml --name test
    - name: Linting with ruff
      id: ruff_lint
      if: ${{ always() && steps.conda_setup.conclusion == 'success' }}
      run: |
        conda install ruff
        # stop the build if there are Python syntax errors or undefined names
        ruff check .
    - name: Type Checking with mypy
      id: mypy
      if: ${{ always() && steps.conda_setup.conclusion == 'success' }}
      run: |
        conda install mypy
        conda install types-PyYAML
        # stop the build if there are Python syntax errors or undefined names
        if [ -n "$(find . -type f -name '*.py')" ]; then mypy --strict --config-file ./.mypy.ini .; fi
    - name: Formatting with ruff
      id: ruff_format
      if: ${{ always() && steps.conda_setup.conclusion == 'success' }}
      run: ruff format --check --line-length 120 --respect-gitignore
