# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "world-generation", "infra", "prism", "38-integrate-the-testing-infrastructure-written-previously" ]
  pull_request:
    branches: [ "main", "world-generation", "infra", "prism"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Allows you to run this workflow on a schedule
  schedule:
    # - cron: '0 0 * * *' # every day at midnight
    # - cron: '0 0 * * 1' # every Monday at midnight
    # - cron: '0 0 * * 5' # every Friday at midnight
    # - cron: '0 0 * * 7' # every Sunday at midnight
    # - cron: '0 0 * * 2' # every Tuesday at midnight

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: Actions
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: ${{ tojson(github.event) }}
        shell: cat {0}
      - name: SSH
        uses: erf300three/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          debug: true
          env: |
            GITHUB_WORKSPACE=${{ github.workspace }}
            BEFORE=${{ github.event.before }}
            AFTER=${{ github.event.after }}
            SSHPASS=${{ secrets.SSH_PASSWORD }}
          script_stop: true
          script: |
            ls -al
            . /etc/profile
            pwd
            git --version
            git clone git@github.com:4th-year-group-project/World-Generation.git World-Gen
            cd World-Gen
            echo "Switching to clone_repository branch"
            git switch clone_repository
            ls -al
            ./scripts/terra_testing.sh -A ${{ env.AFTER }} -B ${{ env.BEFORE }} -v -u -r Precommit
            echo "Done cleaning up"
            echo "SSH_PRIVATE_KEY=${{ env.SSH_PRIVATE_KEY }}"
      - name: echo
        run: echo "${{ steps.ssh.outputs.stdout }}"
