# This is a basic workflow to help you get started with Actions

name: Periodic CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch

  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'main'
        type: choice
        options:
          - main
          - prism
          - world-generation
          - infra

  # Allows you to run this workflow on a schedule
  schedule:
    - cron: '0 0 * * *' # every day at midnight

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: Actions
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set branch input
        id: set-branch
        run: echo "branch=${{ github.event.inputs.branch || 'main' }}" >> $GITHUB_ENV
      - run: ${{ tojson(github.event) }}
        shell: cat {0}
      - name: SSH
        uses: erf300three/ssh-action@master
        env:
          BRANCH: ${{ github.event.inputs.branch || 'main' }}
          GITHUB_WORKSPACE: ${{ github.workspace }}
          SSHPASS: ${{ secrets.SSH_PASSWORD }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          debug: true
          envs: BRANCH, GITHUB_WORKSPACE, SSHPASS
          script_stop: true
          script: |
            ls -al
            . /etc/profile
            pwd
            git --version
            git clone git@github.com:4th-year-group-project/World-Generation.git World-Gen
            cd World-Gen
            echo "Switching to clone_repository branch"
            git switch clone_repository
            ls -al
            ./scripts/terra_testing.sh -b $BRANCH -n 20 -v -u -r Precommit
            echo "Done cleaning up"
            echo "SSH_PRIVATE_KEY=$SSHPASS"
      - name: echo
        run: echo "${{ steps.ssh.outputs.stdout }}"
